[supabase]
supabase_url = "https://vnolrqfkpptpljizzdvw.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZub2xycWZrcHB0cGxqaXp6ZHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTE0NjUsImV4cCI6MjA2OTI4NzQ2NX0.pd-52gKMg-SDTX1nbozG318BP3OR6Ivik5OetOGmRFI"
